# Generated by Django 3.1.7 on 2021-06-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrients',
            old_name='proteins',
            new_name='protein',
        ),
    ]
